 ///TO MAKE CURSOR


let cursor = document.querySelector('#cursor')
let blur = document.querySelector('#cursor-blur')
// Add an event listener for the 'mousemove' event
document.addEventListener('mousemove', (dets) => {
    // 'dets' is the event object generated by the 'mousemove' event
    // 'dets.x' gives the horizontal coordinate of the mouse pointer
    // console.log(dets.x);
    // We subtract 10 to center the cursor
    cursor.style.left = (dets.x - 10) + 'px';
    cursor.style.top = (dets.y - 10) + 'px';
    // We subtract 150 to center the blurred cursor
    blur.style.left = (dets.x - 150) + 'px';
    blur.style.top = (dets.y - 150) + 'px';
  });
  








///TO MAKE ANIMATION IN NAVBAR
let h4all = document.querySelectorAll('.nav-headings h4')
h4all.forEach((elem)=>{
    elem.addEventListener('mouseenter', ()=>{
        cursor.style.scale = 3
        cursor.style.border = '1px solid white'
        cursor.style.backgroundColor = 'transparent'
    })
    elem.addEventListener('mouseleave', ()=>{
        cursor.style.scale = 1
        cursor.style.border = '0'
        cursor.style.backgroundColor = '#95C11E'
    })
})
let button = document.querySelectorAll('button')
button.forEach((elem)=>{
    elem.addEventListener('mouseenter', ()=>{
        cursor.style.scale = 3
        cursor.style.border = '1px solid white'
        cursor.style.backgroundColor = 'transparent'
    })
    elem.addEventListener('mouseleave', ()=>{
        cursor.style.scale = 1
        cursor.style.border = '0'
        cursor.style.backgroundColor = '#95C11E'
    })
})

let card = document.querySelectorAll('.card')
card.forEach((elem)=>{
    elem.addEventListener('mouseenter', ()=>{
        cursor.style.scale = 4
        cursor.style.border = '1px solid white'
        cursor.style.backgroundColor = 'transparent'
    })
    elem.addEventListener('mouseleave', ()=>{
        cursor.style.scale = 1
        cursor.style.border = '0'
        cursor.style.backgroundColor = '#95C11E'
    })
})


let waitingCard = document.querySelectorAll('.card1')
waitingCard.forEach((elem)=>{
    elem.addEventListener('mouseenter', ()=>{
        cursor.style.scale = 3
        cursor.style.border = '1px solid white'
        cursor.style.backgroundColor = 'transparent'
    })
    elem.addEventListener('mouseleave', ()=>{
        cursor.style.scale = 1
        cursor.style.border = '0'
        cursor.style.backgroundColor = '#95C11E'
    })
})

let footer = document.querySelectorAll('#page3 .footer .box h3')
footer.forEach((elem)=>{
    elem.addEventListener('mouseenter', ()=>{
        cursor.style.scale = 3
        cursor.style.border = '1px solid white'
        cursor.style.backgroundColor = 'transparent'
    })
    elem.addEventListener('mouseleave', ()=>{
        cursor.style.scale = 1
        cursor.style.border = '0'
        cursor.style.backgroundColor = '#95C11E'
    })
})

let foot = document.querySelector('#page3 .footer .foot')
foot.addEventListener('mouseenter', ()=>{
    cursor.style.scale = 3
    cursor.style.border = '1px solid white'
    cursor.style.backgroundColor = 'transparent'
})
foot.addEventListener('mouseleave', ()=>{
    cursor.style.scale = 1
    cursor.style.border = '0'
    cursor.style.backgroundColor = '#95C11E'
})














/// TO MAKE SCROLL TRIGGER ANIMATION 
gsap.to("nav", {
    backgroundColor:'rgba(0, 0, 0, 0.9)',
    duration:0.5,
    height:'100px',
    scrollTrigger:{
        trigger:'nav',
        scroller:'body',
        // markers:true,
        start:'top -10%',
        end:'top -11%',
        scrub:1
    }
})
gsap.to("#main", {
    backgroundColor:'rgba(0, 0, 0)',
    duration:1,
    scrollTrigger:{
        trigger:'#main', 
        scroller:'body',
        // markers:true,
        start: 'top -30%',
        end: 'top -70%',
        scrub:3
    }
})
gsap.from('#page2 .about img,.about-in', {
    y:50,
    opacity:0,
    duration:1,
    scrollTrigger:{
        trigger:'#page2 .about',
        scroller:'body', 
        // markers:true,
        start:'top 60%',
        end:'top 55%',
        scrub:3
    }
})
gsap.from('#colon1', {
    y:-70,
    x:-70,
    duration:1,
    scrollTrigger:{
        trigger:'#colon1',
        scroller:'body', 
        // markers:true,
        start:'top 55%',
        end:'top 45%',
        scrub:2
    }
})
gsap.from('#colon2', {
    y:70,
    x:70,
    duration:1,
    scrollTrigger:{
        trigger:'#colon1',
        scroller:'body', 
        // markers:true,
        start:'top 55%',
        end:'top 45%',
        scrub:2
    }
})

gsap.from('#page3 .waiting h1', {
    y:40,
    opacity:0,
    duration:0.5,
    scrollTrigger:{
        trigger:'#page3 .waiting',
        scroller:'body', 
        // markers:true,
        start:'top 65%',
        end:'top 50%',
        scrub:1
    }
})